print("<!DOCTYPE html>")
print("""<html lang="en">""")
print("    <head>")
print("""        <meta charset="UTF-8">""")
print("""        <meta name="viewport" content="width=width=device-width, initial-scale=1.0">""")
print("        <title>Document</title>")
print("""        <link rel="stylesheet" href="style.css">""")
print("""        <script src="script.js" defer></script>""")
print("    </head>")
print("    <body>")
print("        ")
print("    </body>")       
print("</html>")

