print("<DOCTYPE html>")
print("<html lang="en">")
print("     <head>")
print("         <meta charset="UTF-8">")
print("         <meta name="viewport" content="width=device-width, initial-scale=1.0">")
print("         <title>Calculator</title>")
print("         <link rel="stylesheet" href="style.css">")
print("         <script src="script.js" defer></script>")
print("     </head>")
print("     <body>")
print("         <div class="box">")
print("             <div class="display">")
print("         </div>")
print("         <div class="buttons">")
print("     <body>")
print("</html>")
